### ISSUE TITLE
I wonder if any Ethernet-based protocol will work? E.g. ethercat

### ISSUE THREAD

**Issue by LoveChunHua** [jemcek/packETH#21]

**Comment by jemcek** [comment]
yes, of course. you just need to select user defined under ethertype and put 88a4 inside and then build the rest of the packets. or just load captured ethercat frame saved in pcap format and resend it.

**Comment by jemcek** [comment]
Hi Jonathan, 

I just made a fresh installation of Ubunto 20.04 deskop and then followed the commands in this order as stated on the github. I didn’t have any problems isntalling packeth

sudo apt install git
git clone https://github.com/jemcek/packETH.git
cd packETH/
sudo apt-get install build-essential
sudo apt-get install autoconf
sudo apt-get install pkg-config
sudo apt-get install gtk+2.0
./autogen.sh 
./configure 
make
./packETH 

Additional installation of aclocal, autoheader and automake was not necessary since they were already installed with autoconf. 

So I don’t have any idea what could be different on your system. Maybe you did some other isntallations in the past that could ruin the lib dependencies for packeth.
So I can only suggest you to try a fresh installation and try again. 

Also you could run "autoreconf -f -i “ after autogen.sh this helps sometimes if some files are broken. 

Regards, Miha
